name: Automated Deployment

on:
  push:
    branches:
      - main
      - feat/gh-actions

env:
  NODE_VERSION: 16

jobs:
  test-app:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Get the code from the repo
        uses: actions/checkout@v3
      - name: Set node version - "${{ env.NODE_VERSION }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE_VERSION }}"
          cache: "yarn"
      - name: Install dependencies
        run: |
          cd frontend
          yarn install
      - name: Test app
        run: |
          cd frontend 
          npx nuxi prepare && yarn test

  build-app:
    needs: ["test-app"]
    strategy:
      matrix:
        node-version: "${{ env.NODE_VERSION }}"
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get the code from the repo
        uses: actions/checkout@v3
      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: |
          cd frontend
          yarn install
      - name: Build app
        run: |
          cd frontend
          yarn build
          tar -czf "${{ github.sha }}".tar.gz .output
      - name: Store frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: front-build
          path: ./frontend/.output
