name: Deploy Nuxt app
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code from the repo
        uses: actions/checkout@v3
      - name: Set node version (16)
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install dependencies
        run: |
          cd frontend
          yarn install
      - name: Test app
        run: |
          cd frontend 
          npx nuxi prepare && yarn test
  build:
    needs: ["test"]
    strategy:
      matrix:
        node-version: [14, 16, 18]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get the code from the repo
        uses: actions/checkout@v3
      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: |
          cd frontend
          yarn install
      - name: Build app
        run: |
          cd frontend
          yarn build
      - name: Deploy
        run: echo Deploying...
