name: Test Nuxt app
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Get the code from the repo
        uses: actions/checkout@v3
      - name: Set node version (16)
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          cd frontend
          yarn install
      - name: Test app
        run: |
          ls -a
          cd frontend 
          yarn test
