name: Test Nuxt app
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Get the code from the repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd frontend
          yarn install
      - name: Test app
        run: |
          cd frontend 
          yarn test
